### PR TITLE
Add Laravel 9 Support

### PR DESCRIPTION
**Pull request by AlexAzartsev**

### CODE REVIEW

**Comment by aarondfrancis** [comment]
@AlexAzartsev thanks for doing this! I'm curious why you bumped the minimum version of PHP 8 to PHP 8.0.2. Was that on purpose? I rolled it back for now, but I'm happy to re-apply it if there's a reason!

**Comment by AlexAzartsev** [comment]
@aarondfrancis, thx for merge my changes, laravel 9 has minimum required version of php 8.0.2
you can find this info in official docs:
[https://laravel.com/docs/9.x/upgrade#updating-dependencies](https://laravel.com/docs/9.x/upgrade#updating-dependencies)
I don't know why exactly they decided to use this version as minimum required, but I just followed their guides :)
I'm pretty sure you can keep 8.0 as minimum in your package.

**Comment by aarondfrancis** [comment]
Ha well that's a pretty good reason! Thanks for the link. I'll probably leave it because Laravel 8 can presumably run on 8.0.0? In reality either way probably won't have any effect on anyone! 

Thanks again 😄

**Comment by AlexAzartsev** [comment]
Yep, it is true, 8.0 will be better for previous versions.
Thx you your package :)

**Comment by AlexAzartsev** [comment]
@aarondfrancis please make a new release with these changes, so I can switch back to use your package in composer.json instead of  my fork, thx :)

**Comment by benholmen** [comment]
@aarondfrancis I'll give you a Tightenbuck if you tag this today 🚀

**Pull request merged**
